title: Test Blog # The title of the blog
author: Tim Beran # Your name 
email: timothymberan@gmail.com # your email shown in the footer
url: https://tberan.github.io/ # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
  A test blog for a personal project that I may turn into a legitimate one down the road.
favicon: "./favicon.ico" # set the favicon of the site 

show_excerpts: false # set to true to show excerpts on the homepage
  
# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: "assets/images/180px-The_Cheat_Character_Video.png" # avatar in about page
  about_you: my about page ¯\_( ͠° ͟ʖ °͠ )_/¯ # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    # twitter: 
    github: tberan
    rss: RSS
    # dribbble: 
    # facebook: huangyz0918
    # flickr:   
    # instagram: 
    # linkedin: yizheng-huang
    # pinterest: 
    # youtube: 
    # youtube_channel: 
    # youtube_channel_name: 
    # telegram: 
    # googleplus: 
    # microdotblog: 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

# Build settings
remote_theme: huangyz0918/moving # note, please use huangyz0918/moving if you want to publish to Github Pages.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
